# Generated by Django 2.1.3 on 2018-11-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='category_id',
            new_name='mealcategory_id',
        ),
    ]
