# Generated by Django 2.1.3 on 2018-11-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_remove_check_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mealsid',
        ),
        migrations.AddField(
            model_name='order',
            name='mealsid',
            field=models.ManyToManyField(related_name='orders', to='meal.Meal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tablename',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meal.Table'),
        ),
    ]
