# Generated by Django 2.1.3 on 2018-11-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_auto_20181115_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tablename',
        ),
    ]
