# Generated by Django 2.1.3 on 2018-11-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_order_tablename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealstoorder',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
