# Generated by Django 2.1.3 on 2018-11-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_auto_20181115_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealstoorder',
            name='meals',
        ),
        migrations.AddField(
            model_name='mealstoorder',
            name='meals',
            field=models.ManyToManyField(related_name='mealstoorders', to='meal.Meal'),
        ),
    ]
