# Generated by Django 2.1.3 on 2018-11-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0013_auto_20181115_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='meals',
            field=models.ManyToManyField(to='meal.Meal'),
        ),
    ]
