# Generated by Django 2.1.3 on 2018-11-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0020_check_meals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='check',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mealsid',
        ),
        migrations.AddField(
            model_name='order',
            name='mealsid',
            field=models.ManyToManyField(related_name='orders', to='meal.Meal'),
        ),
    ]
