# Generated by Django 2.1.3 on 2018-11-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0021_auto_20181115_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mealsid',
        ),
    ]
