# Generated by Django 2.1.3 on 2018-11-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0022_remove_order_mealsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='check',
            name='servicefee',
        ),
        migrations.RemoveField(
            model_name='mealstoorder',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='mealstoorder',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isitopen',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tableid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiterid',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='MealsToOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
