# Generated by Django 2.1.3 on 2018-11-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0024_auto_20181115_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mealsid',
            field=models.ManyToManyField(related_name='orders', to='meal.Meal'),
        ),
    ]
