# Generated by Django 2.1.3 on 2018-11-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0026_check_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='meals',
            field=models.ManyToManyField(default=0, to='meal.MealsToOrder'),
        ),
    ]
