# Generated by Django 2.1.3 on 2018-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0031_auto_20181116_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='orderid',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='orderid',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mealsid',
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.ManyToManyField(through='meal.MealsToOrder', to='meal.Meal'),
        ),
    ]
