# Generated by Django 2.1.3 on 2018-11-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0033_auto_20181116_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealstoorder',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealstoorders', to='meal.Meal'),
        ),
        migrations.AlterField(
            model_name='mealstoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealstoorders', to='meal.Order'),
        ),
    ]
