# Generated by Django 2.1.3 on 2018-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0034_auto_20181116_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='order',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='mealstoorder',
            old_name='order',
            new_name='orderid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meals',
        ),
        migrations.AddField(
            model_name='order',
            name='mealsid',
            field=models.ManyToManyField(related_name='orders', through='meal.MealsToOrder', to='meal.Meal'),
        ),
    ]
