# Generated by Django 2.1.3 on 2018-11-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0035_auto_20181116_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tablename',
            field=models.CharField(default='table1', max_length=250),
        ),
    ]
